export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    CART_LIST: "CART_LIST",
    SHOW_PRODUCTS: "SHOW_PRODUCTS",
    FORM_ADDRESS: "FORM_ADDRESS",
    FORM_PAYMENT: "FORM_PAYMENT",
    FORM_INVOICE: "FORM_INVOICE"
};